root: /home/yan/EmbodiedAgent/generate_data/pair_models/point_cloud
task: custom  # This is one of the 6 tasks - depends on the action class.
action_class: 0  # This is the action class for the task.
train_folder: train_data
test_folder: test_data
data_fn: valid_pcs_list.txt

train_dset:
  dataset_type: total_pcs_pretraining
  dataset_root: ${..root}/${..train_folder}
  dataset_indices: null
  cloud_type: final
  action_class: ${..action_class}
  num_points: 1024
  data_size: 1024
  pc_aug: True
  phase: train
  data_fn: train_${..data_fn}
  shuffle_pcs: True

val_dset:
  dataset_type: ${..train_dset.dataset_type}
  dataset_root: ${..root}/${..test_folder}
  dataset_indices: ${..train_dset.dataset_indices}
  cloud_type: ${..train_dset.cloud_type}
  action_class: ${..train_dset.action_class}
  num_points: ${..train_dset.num_points}
  pc_aug: True
  phase: test
  data_fn: test_${..data_fn}
  shuffle_pcs: False
  data_size: 1024